import type { FeedPost } from "@/components/feed/feed-card";
import type { CommentData } from "@/components/feed/comment-thread";

// ─── Sources ───
export const mockSources = [
  {
    name: "SupplementHQ",
    slug: "supplementhq",
    url: "supplementhq.co.uk",
    verified: true,
    avgRating: 4.8,
    reviewCount: 342,
    description: "One of the UK's most trusted supplement retailers. Fast shipping, genuine products, and excellent customer service. Specialising in protein, creatine, and performance supplements.",
    categories: ["Protein", "Creatine", "Pre-Workout"],
  },
  {
    name: "PureProtein UK",
    slug: "pureprotein-uk",
    url: "pureprotein.co.uk",
    verified: true,
    avgRating: 4.6,
    reviewCount: 218,
    description: "Premium protein supplements sourced directly from manufacturers. Known for competitive pricing on whey and casein products.",
    categories: ["Protein", "Amino Acids"],
  },
  {
    name: "VitalStack",
    slug: "vitalstack",
    url: "vitalstack.com",
    verified: false,
    avgRating: 4.5,
    reviewCount: 156,
    description: "Comprehensive supplement store offering vitamins, minerals, and specialty stacks. Wide product range with international shipping.",
    categories: ["Vitamins", "Minerals", "Stacks"],
  },
  {
    name: "NutriDirect",
    slug: "nutridirect",
    url: "nutridirect.co.uk",
    verified: true,
    avgRating: 4.3,
    reviewCount: 89,
    description: "Direct-to-consumer supplement retailer with a focus on nootropics and cognitive enhancement products.",
    categories: ["Nootropics", "Vitamins"],
  },
  {
    name: "GainZone",
    slug: "gainzone",
    url: "gainzone.com",
    verified: false,
    avgRating: 4.1,
    reviewCount: 67,
    description: "Sports nutrition specialist. Great for bulk buying protein and creatine at wholesale prices.",
    categories: ["Protein", "Creatine", "Mass Gainers"],
  },
  {
    name: "ProteinWorks",
    slug: "proteinworks",
    url: "proteinworks.co.uk",
    verified: true,
    avgRating: 4.7,
    reviewCount: 412,
    description: "Award-winning sports nutrition brand. Custom protein blends and a huge range of flavours. Great loyalty programme.",
    categories: ["Protein", "Snacks", "Bundles"],
  },
  {
    name: "MyVitamins",
    slug: "myvitamins",
    url: "myvitamins.com",
    verified: true,
    avgRating: 4.2,
    reviewCount: 198,
    description: "Part of THG group. Affordable vitamins and minerals with frequent sales events. Good range of beauty supplements.",
    categories: ["Vitamins", "Minerals", "Beauty"],
  },
  {
    name: "BulkPowders",
    slug: "bulkpowders",
    url: "bulk.com",
    verified: true,
    avgRating: 4.4,
    reviewCount: 567,
    description: "One of Europe's leading sports nutrition brands. Great value protein powders, pre-workouts, and accessories.",
    categories: ["Protein", "Pre-Workout", "Creatine"],
  },
  {
    name: "Holland & Barrett",
    slug: "holland-barrett",
    url: "hollandandbarrett.com",
    verified: true,
    avgRating: 3.9,
    reviewCount: 834,
    description: "High street health food chain with an extensive online presence. Wide supplement range but prices can be higher than specialist retailers.",
    categories: ["Vitamins", "Minerals", "Herbal"],
  },
];

// ─── Products ───
export const mockProducts = [
  {
    name: "Gold Standard Whey",
    slug: "gold-standard-whey",
    brandName: "Optimum Nutrition",
    brandSlug: "optimum-nutrition",
    category: "Protein",
    avgRating: 4.7,
    reviewCount: 1243,
    description: "The world's best-selling whey protein powder. 24g protein per serving with 5.5g BCAAs and 4g glutamine. Available in 20+ flavours.",
    ingredients: "Whey Protein Blend (Whey Protein Isolate, Whey Protein Concentrate, Whey Peptides), Cocoa Powder, Natural and Artificial Flavours, Lecithin, Aminogen®, Lactase",
    dosage: "1 scoop (30.4g) mixed with 180-240ml of cold water or milk. Take 1-2 servings daily.",
  },
  {
    name: "Creatine Monohydrate",
    slug: "creatine-monohydrate",
    brandName: "Creapure",
    brandSlug: "creapure",
    category: "Creatine",
    avgRating: 4.9,
    reviewCount: 876,
    description: "Ultra-pure creatine monohydrate manufactured in Germany. Micronised for better solubility. The gold standard of creatine supplementation.",
    ingredients: "100% Creatine Monohydrate (Creapure®)",
    dosage: "5g daily mixed with water or juice. No loading phase required.",
  },
  {
    name: "Omega-3 Fish Oil",
    slug: "omega-3-fish-oil",
    brandName: "Nordic Naturals",
    brandSlug: "nordic-naturals",
    category: "Vitamins",
    avgRating: 4.5,
    reviewCount: 432,
    description: "Molecularly distilled fish oil providing 1000mg EPA and 500mg DHA per serving. Third-party tested for purity.",
    ingredients: "Fish Oil (from Anchovies and Sardines), Softgel Capsule (Gelatin, Glycerin, Water), Natural Lemon Flavour, d-Alpha Tocopherol, Rosemary Extract",
    dosage: "2 softgels daily with food.",
  },
  {
    name: "Vitamin D3 4000IU",
    slug: "vitamin-d3-4000iu",
    brandName: "Solgar",
    brandSlug: "solgar",
    category: "Vitamins",
    avgRating: 4.6,
    reviewCount: 321,
    description: "High-strength vitamin D3 for immune support, bone health, and mood regulation. Cholecalciferol form for maximum absorption.",
    ingredients: "Vitamin D3 (as Cholecalciferol) 100mcg (4000IU), Safflower Oil, Softgel Capsule (Bovine Gelatin, Glycerin, Water)",
    dosage: "1 softgel daily with a meal containing fat.",
  },
  {
    name: "C4 Original Pre-Workout",
    slug: "c4-original-pre-workout",
    brandName: "Cellucor",
    brandSlug: "cellucor",
    category: "Pre-Workout",
    avgRating: 4.2,
    reviewCount: 678,
    description: "America's #1 selling pre-workout. Contains caffeine, beta-alanine, and creatine nitrate for explosive energy and performance.",
    ingredients: "CarnoSyn® Beta-Alanine 1.6g, Creatine Nitrate 1g, Caffeine Anhydrous 150mg, Arginine AKG 1g",
    dosage: "Mix 1 scoop with 180-240ml water 20-30 minutes before training.",
  },
  {
    name: "BCAA Complex",
    slug: "bcaa-complex",
    brandName: "MyProtein",
    brandSlug: "myprotein",
    category: "Amino Acids",
    avgRating: 4.3,
    reviewCount: 234,
    description: "Essential branched-chain amino acids in a 2:1:1 ratio. Supports muscle recovery and reduces fatigue during training.",
    ingredients: "L-Leucine, L-Isoleucine, L-Valine, Citric Acid, Natural Flavouring, Sucralose",
    dosage: "5g mixed with 300ml water during or after training.",
  },
];

// ─── Brands ───
export const mockBrands = [
  {
    name: "Optimum Nutrition",
    slug: "optimum-nutrition",
    website: "optimumnutrition.com",
    country: "United States",
    verified: true,
    description: "Industry-leading sports nutrition brand since 1986. Famous for Gold Standard Whey — the world's best-selling protein powder. Part of Glanbia Performance Nutrition.",
    productCount: 45,
    avgRating: 4.6,
    totalReviews: 3200,
  },
  {
    name: "MyProtein",
    slug: "myprotein",
    website: "myprotein.com",
    country: "United Kingdom",
    verified: true,
    description: "Europe's #1 online sports nutrition brand. Huge product range at competitive prices. Known for frequent sales and a massive flavour selection.",
    productCount: 120,
    avgRating: 4.3,
    totalReviews: 5400,
  },
  {
    name: "Creapure",
    slug: "creapure",
    website: "creapure.com",
    country: "Germany",
    verified: true,
    description: "The gold standard in creatine manufacturing. Made in Germany using a patented synthesis process that ensures the highest purity creatine monohydrate on the market.",
    productCount: 3,
    avgRating: 4.9,
    totalReviews: 1200,
  },
];

// ─── Communities ───
export const mockCommunities = [
  {
    slug: "sourcereviews",
    name: "Source Reviews",
    description: "Share your experiences with supplement retailers and online sellers. Help the community find trustworthy sources.",
    memberCount: 12400,
    rules: [
      { title: "Be honest and fair", description: "Only review sources you've actually purchased from. Provide specific details about your experience." },
      { title: "No self-promotion", description: "Business owners cannot review their own source. Use the 'Claim Source' feature instead." },
      { title: "Include evidence", description: "Screenshots of orders, packaging photos, and lab test results are encouraged." },
      { title: "One review per source per 7 days", description: "Avoid spam by limiting reviews to once per week per source." },
    ],
    postTypes: ["source_review", "discussion"] as const,
  },
  {
    slug: "supplementreviews",
    name: "Supplement Reviews",
    description: "In-depth reviews of supplement products. Share your experience with specific products, brands, and formulations.",
    memberCount: 8900,
    rules: [
      { title: "Include usage details", description: "Mention how long you've used the product, dosage, and any effects noticed." },
      { title: "Be specific", description: "Name the exact product, brand, and flavour you're reviewing." },
      { title: "No medical claims", description: "Share personal experience but don't make medical claims or diagnoses." },
    ],
    postTypes: ["product_review", "discussion"] as const,
  },
  {
    slug: "sourcetalk",
    name: "Source Talk",
    description: "General discussion about supplements, sources, and the industry. Ask questions, share tips, and discuss trends.",
    memberCount: 6200,
    rules: [
      { title: "Stay on topic", description: "Keep discussions related to supplements, nutrition, and health." },
      { title: "Be respectful", description: "Disagree with ideas, not people. No personal attacks." },
      { title: "Search first", description: "Check if your question has been answered before posting." },
    ],
    postTypes: ["discussion", "deal", "image_post"] as const,
  },
  {
    slug: "ukprotein",
    name: "UK Protein",
    description: "Dedicated to UK-based protein enthusiasts. Local source recommendations, deals, and product comparisons.",
    memberCount: 3100,
    rules: [
      { title: "UK focus", description: "Keep discussions relevant to UK-available products and sources." },
    ],
    postTypes: ["discussion", "source_review", "product_review", "deal"] as const,
  },
  {
    slug: "preworkout",
    name: "Pre-Workout",
    description: "Everything pre-workout. Reviews, comparisons, stacking advice, and stim-free alternatives.",
    memberCount: 2800,
    rules: [
      { title: "Dosage safety", description: "Always mention product dosages and don't encourage exceeding recommended amounts." },
    ],
    postTypes: ["product_review", "discussion"] as const,
  },
];

// ─── Feed Posts ───
export const mockFeedPosts: FeedPost[] = [
  {
    id: "post-1",
    post_type: "source_review",
    title: "SupplementHQ review — fast delivery, legit products",
    body: "Ordered creatine monohydrate and whey protein last week. Arrived in 2 days, well packaged. Both products had batch codes that checked out on the manufacturer's website. Will definitely order again. The checkout process was smooth and they even included a free sample of their new BCAA formula.",
    community: "sourcereviews",
    communityName: "Source Reviews",
    author: "ProteinPete",
    authorTier: "gold",
    rating: 5,
    upvotes: 47,
    downvotes: 2,
    commentCount: 12,
    created: "3h ago",
    sourceName: "SupplementHQ",
    sourceUrl: "supplementhq.co.uk",
  },
  {
    id: "post-2",
    post_type: "product_review",
    title: "Optimum Nutrition Gold Standard Whey — Still the GOAT?",
    body: "Been using ON Gold Standard for years but recently tried a few alternatives. Here's my honest comparison after 3 months of testing different brands. Mixability is still unmatched, flavour selection is huge, and the macros are solid. Only downside is the price has crept up significantly.",
    community: "supplementreviews",
    communityName: "Supplement Reviews",
    author: "FitReviewer",
    authorTier: "platinum",
    rating: 4,
    upvotes: 134,
    downvotes: 8,
    commentCount: 45,
    created: "5h ago",
    productName: "Gold Standard Whey",
    brandName: "Optimum Nutrition",
  },
  {
    id: "post-3",
    post_type: "discussion",
    title: "Best UK sources for nootropics in 2026?",
    body: "Looking for reliable UK-based sources for nootropics. Specifically interested in Lion's Mane and Ashwagandha KSM-66. What are people using? I've tried a couple of sources but quality seems inconsistent. Would love recommendations from people who've had their products independently tested.",
    community: "sourcetalk",
    communityName: "Source Talk",
    author: "BrainGains",
    authorTier: "silver",
    upvotes: 23,
    downvotes: 1,
    commentCount: 31,
    created: "8h ago",
  },
  {
    id: "post-4",
    post_type: "source_review",
    title: "Warning: Avoid NutriScam.co — possible counterfeit products",
    body: "Ordered what was supposed to be branded creatine but the packaging looked off. Different font on the label, no batch number visible, and the powder had a slightly different texture. Sent it for testing through a third-party lab and the results were concerning — significantly under-dosed and contained fillers.",
    community: "sourcereviews",
    communityName: "Source Reviews",
    author: "SafeSupps",
    authorTier: "diamond",
    rating: 1,
    upvotes: 289,
    downvotes: 3,
    commentCount: 67,
    created: "12h ago",
    sourceName: "NutriScam",
    sourceUrl: "nutriscam.co",
  },
  {
    id: "post-5",
    post_type: "deal",
    title: "30% off all Creatine at ProteinWorks — code SPRING30",
    body: "Just spotted this on their website. 30% off the entire creatine range including their premium Creapure® monohydrate. I've used their creatine before and it's legit — dissolves well and no grittiness. Stack it with the free delivery over £30 for extra savings.",
    community: "sourcetalk",
    communityName: "Source Talk",
    author: "DealHunter",
    authorTier: "gold",
    upvotes: 56,
    downvotes: 1,
    commentCount: 8,
    created: "1d ago",
    sourceName: "ProteinWorks",
    dealPrice: "30% OFF",
    dealExpires: "2026-04-05T23:59:59Z",
    dealUrl: "https://proteinworks.co.uk",
  },
  {
    id: "post-6",
    post_type: "product_review",
    title: "Creapure Creatine Monohydrate — pure and simple",
    body: "You can't go wrong with Creapure. It's just 100% pure creatine monohydrate, no fillers, no additives. German-manufactured with strict quality control. The micronised version dissolves perfectly in water. I've been using 5g daily for 6 months now and the performance gains are undeniable.",
    community: "supplementreviews",
    communityName: "Supplement Reviews",
    author: "StrengthScience",
    authorTier: "platinum",
    rating: 5,
    upvotes: 98,
    downvotes: 2,
    commentCount: 22,
    created: "1d ago",
    productName: "Creatine Monohydrate",
    brandName: "Creapure",
  },
];

// ─── Comments ───
export const mockComments: CommentData[] = [
  {
    id: "c1",
    author: "GymRat42",
    authorTier: "silver",
    body: "Great review! I had the same experience with their shipping speed. Ordered Monday evening and it arrived Wednesday morning. Can't complain at all.",
    upvotes: 12,
    downvotes: 0,
    created: "2h ago",
    children: [
      {
        id: "c1-1",
        author: "ProteinPete",
        authorTier: "gold",
        body: "Thanks! Yeah their dispatch is impressively quick. I think they have a warehouse near me which helps.",
        upvotes: 5,
        downvotes: 0,
        created: "1h ago",
        children: [
          {
            id: "c1-1-1",
            author: "SuppsAddict",
            authorTier: "bronze",
            body: "Where are they based? I'm in the Midlands and wondering if I'd get similar delivery times.",
            upvotes: 2,
            downvotes: 0,
            created: "45m ago",
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: "c2",
    author: "NutritionNerd",
    authorTier: "platinum",
    body: "Did you verify the batch codes? I always check mine through the manufacturer's website. Glad to hear they're legit — some sources have been selling expired stock recently.",
    upvotes: 18,
    downvotes: 1,
    created: "1h ago",
    children: [
      {
        id: "c2-1",
        author: "ProteinPete",
        authorTier: "gold",
        body: "Yep, both checked out. Manufactured within the last 3 months and expiry dates are well into 2027.",
        upvotes: 8,
        downvotes: 0,
        created: "45m ago",
        children: [],
      },
    ],
  },
  {
    id: "c3",
    author: "BargainSpotter",
    authorTier: "gold",
    body: "Their prices are decent too. Not always the cheapest but the combination of genuine products, fast shipping, and good customer service makes it worth any small premium IMO.",
    upvotes: 7,
    downvotes: 2,
    created: "30m ago",
    children: [],
  },
];

// ─── Rating distributions ───
export const mockSourceRatingDistribution = [
  { stars: 5, count: 186 },
  { stars: 4, count: 98 },
  { stars: 3, count: 34 },
  { stars: 2, count: 15 },
  { stars: 1, count: 9 },
];

export const mockProductRatingDistribution = [
  { stars: 5, count: 687 },
  { stars: 4, count: 342 },
  { stars: 3, count: 124 },
  { stars: 2, count: 56 },
  { stars: 1, count: 34 },
];

// ─── Categories ───
export const mockCategories = [
  { name: "Protein", slug: "protein", icon: "💪" },
  { name: "Creatine", slug: "creatine", icon: "⚡" },
  { name: "Vitamins", slug: "vitamins", icon: "🍊" },
  { name: "Pre-Workout", slug: "pre-workout", icon: "🔥" },
  { name: "Nootropics", slug: "nootropics", icon: "🧠" },
  { name: "Amino Acids", slug: "amino-acids", icon: "🧬" },
  { name: "Minerals", slug: "minerals", icon: "💎" },
  { name: "Herbal", slug: "herbal", icon: "🌿" },
];
